name: pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    - name: Setup Firefox
      uses: abhi1693/setup-browser@v0.3.5
      with:
        browser: firefox
        version: latest
    - name: Start local web application for tests
      run: |
        echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV
        nohup python tests/web_app/app.py &
    - name: Delay before running tests
      run: |
        sleep 5
    - name: Run tests
      run: |
        coverage run -m pytest tests -v
    - name: Coverage report
      run: |
        coverage report --show-missing
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3